feat-release-fix: Release Fix flow

diff --git a/.github/workflows/github-actions-release-fix.yml b/.github/workflows/github-actions-release-fix.yml
--- a/.github/workflows/github-actions-release-fix.yml
+++ b/.github/workflows/github-actions-release-fix.yml
@@ -1,11 +1,17 @@
 name: Fix Release
 run-name: Release ${{ github.run_number }} fix was triggered by ${{ github.actor }} on ${{ github.event_name }} event
 
-env:
-  RELEASE_VERSION: ${{ github.run_number }}
-
 on:
   workflow_dispatch:
+    inputs:
+      release_version:
+        description: 'Release version (number)'
+        required: true
+
+env:
+  RELEASE_VERSION: ${{ github.event.inputs.release_version }}
+  FIX_VERSION: ${{ github.run_number }}
+  BRANCH_NAME: "releases/${{ github.event.inputs.release_version }}"
 
 jobs:
   linter-checks:
@@ -14,6 +20,8 @@ jobs:
     steps:
       - name: Clone repository
         uses: actions/checkout@v4
+        with:
+          ref: ${{ env.BRANCH_NAME }}
 
       - name: Set up Node.js
         uses: actions/setup-node@v4
@@ -32,6 +40,8 @@ jobs:
     steps:
       - name: Clone repository
         uses: actions/checkout@v4
+        with:
+          ref: ${{ env.BRANCH_NAME }}
 
       - name: Set up Node.js
         uses: actions/setup-node@v4
@@ -44,41 +54,11 @@ jobs:
       - name: Run tests
         run: npm run test
 
-  create-release-branch:
+  build-and-push-docker-image:
     runs-on: ubuntu-latest
     needs:
       - linter-checks
       - tests-checks
-
-    outputs:
-      BRANCH_NAME: ${{ steps.set_branch_name.outputs.BRANCH_NAME }}
-
-    steps:
-      - name: Clone repository
-        uses: actions/checkout@v4
-        with:
-          ref: main
-
-      - name: Configure Git
-        run: |
-          git config --global user.name "Shri-Deploy-Bot"
-          git config --global user.email "igorbarbashov@yandex.ru"
-
-      - name: Set Release branch name
-        id: set_branch_name
-        run: echo "BRANCH_NAME=releases/${{ env.RELEASE_VERSION }}" >> $GITHUB_ENV
-
-      - name: Create new branch
-        run: |
-          git checkout -b ${{ env.BRANCH_NAME }}
-          git push origin ${{ env.BRANCH_NAME }}
-
-      - name: Echo job name
-        run: echo "Create Release branch ${{ env.BRANCH_NAME }}"
-
-  build-and-push-docker-image:
-    runs-on: ubuntu-latest
-    needs: create-release-branch
 
     env:
       PORT: ${{ vars.PORT }}
@@ -90,7 +70,7 @@ jobs:
       - name: Clone repository
         uses: actions/checkout@v4
         with:
-          ref: ${{ needs.create-release-branch.outputs.BRANCH_NAME }}
+          ref: ${{ env.BRANCH_NAME }}
 
       - name: Set up Node.js
         uses: actions/setup-node@v4
@@ -108,8 +88,8 @@ jobs:
 
       - name: Tag and push Docker images
         run: |
-          docker tag ${{ env.IMAGE_NAME }} "cr.yandex/${{ secrets.CONTAINER_REGISTRY_ID }}/app:${{ env.RELEASE_VERSION }}"
-          docker push "cr.yandex/${{ secrets.CONTAINER_REGISTRY_ID }}/app:${{ env.RELEASE_VERSION }}"
+          docker tag ${{ env.IMAGE_NAME }} "cr.yandex/${{ secrets.CONTAINER_REGISTRY_ID }}/app:${{ env.RELEASE_VERSION }}_fix${{ env.FIX_VERSION }}"
+          docker push "cr.yandex/${{ secrets.CONTAINER_REGISTRY_ID }}/app:${{ env.RELEASE_VERSION }}_fix${{ env.FIX_VERSION }}"
           docker tag ${{ env.IMAGE_NAME }} "cr.yandex/${{ secrets.CONTAINER_REGISTRY_ID }}/app:${{ env.RELEASE_VERSION }}_latest"
           docker push "cr.yandex/${{ secrets.CONTAINER_REGISTRY_ID }}/app:${{ env.RELEASE_VERSION }}_latest"
 
@@ -122,7 +102,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           ssh-key: ${{ secrets.DEPLOY_KEY }}
-          ref: main
+          ref: ${{ env.BRANCH_NAME }}
 
       - name: Configure Git
         run: |
@@ -132,7 +112,7 @@ jobs:
       - name: Create Tag
         run: |
           git fetch --tags
-          git tag -a "v${{ env.RELEASE_VERSION }}" -m "Release version ${{ env.RELEASE_VERSION }}"
+          git tag -a "v${{ env.RELEASE_VERSION }}_fix${{ env.FIX_VERSION }}" -m "Fix ${{ env.FIX_VERSION }} for Release version ${{ env.RELEASE_VERSION }}"
           git push origin --tags
 
       - name: Update CHANGELOG.md
@@ -158,6 +138,9 @@ jobs:
             git add CHANGELOG.md
             git commit -m "$commit_message"
             git push origin main
+          else
+            echo "There are no tags"
+            exit 1
           fi
 
       - name: Create Label for Release Issue
@@ -165,16 +148,20 @@ jobs:
           GH_TOKEN: ${{ github.token }}
         run: gh label create "v${{ env.RELEASE_VERSION }}" --color "f29513" --description "Label for Release v${{ env.RELEASE_VERSION }}"
 
-      - name: Create Release Issue
+      - name: Add comment to Release Issue
         env:
           GH_TOKEN: ${{ github.token }}
         run: |
-          commit_list=$(cat ${{ env.COMMIT_LIST_FILE }})
-          gh issue create \
-            --title "Release v${{ env.RELEASE_VERSION }}" \
-            --body "$(echo -e "**Date:** $(date -u +"%Y-%m-%d")<br> \
+          issue_id=$(gh issue list --label "v${{ env.RELEASE_VERSION }}" --json number --jq '.[0].number')
+          if [ -n "$issue_id" ]; then
+            commit_list=$(cat ${{ env.COMMIT_LIST_FILE }})
+            gh issue comment $issue_id --body "$(echo -e "**Date:** $(date -u +"%Y-%m-%d")<br> \
               **Author:** ${{ github.actor }}<br> \
               **Version:** ${{ env.RELEASE_VERSION }}<br> \
               **Commits:**<br><br>${commit_list}<br> \
-              **Docker Image:** cr.yandex/${{ secrets.CONTAINER_REGISTRY_ID }}/app:${{ env.RELEASE_VERSION }}")" \
-            --label "v${{ env.RELEASE_VERSION }}"
+              **Docker Image:** cr.yandex/${{ secrets.CONTAINER_REGISTRY_ID }}/app:${{ env.RELEASE_VERSION }}_fix${{ env.FIX_VERSION }}<br> \
+              **Docker Image Latest:** cr.yandex/${{ secrets.CONTAINER_REGISTRY_ID }}/app:${{ env.RELEASE_VERSION }}_latest")"
+          else
+            echo "Issue with label v${{ env.RELEASE_VERSION }} not found."
+            exit 1
+          fi
